sqlite: &sqlite
  adapter: sqlite3
  database: db/<%= Rails.env %>.sqlite3

mysql: &mysql
  adapter: mysql2
  database: "<%=ENV['OPENSHIFT_APP_NAME']%>"
  username: "<%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>"
  password: "<%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>"
  host:     <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>

postgresql: &postgresql
  adapter: postgresql
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_POSTGRESQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_POSTGRESQL_DB_PASSWORD']%>
  host:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_POSTGRESQL_DB_PORT']%>
  min_messages: ERROR
  reconnect: false

#defaults: &defaults
#  pool: 5
#  timeout: 5000
#  encoding: utf8
#  <<: *<%= ENV['RAILS_DB'] || "sqlite" %>
 
#Default configuration to local machine fedora, database IRBDB 
defaults: &defaults
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /opt/lampp/var/mysql/mysql.sock

#Default configuration to CLOUD9, database c9
#defaults: &defaults
#  adapter: mysql2
#  encoding: utf8
#  database: c9
#  username: <%=ENV['C9_USER']%>
#  host: <%=ENV['IP']%>

development:
  <<: *defaults
  database: IRBDB

test: &test
  <<: *defaults

production:
  <<: *mysql
